### ISSUE TITLE
Thrown: TypeError: Cannot read property 'hour' of undefined     at Function.getKhNewYearMoment (/Users/mac/Desktop/Projects/momentkh/momentkh.js:616:79)

### ISSUE THREAD

**Issue by ThyrithSor** [ThyrithSor/momentkh#11]
It shows the following error:
```
Thrown:
TypeError: Cannot read property 'hour' of undefined
    at Function.getKhNewYearMoment (/Users/mac/Desktop/Projects/momentkh/momentkh.js:616:79)
```
#### reproducing error
```js
moment.getKhNewYearMoment(2032);
```

**Comment by ThyrithSor** [comment]
ឆ្នាំ ២០៣២ មាន សុទិន២ ដែលមានអង្សារស្មើ០ ដែលមួយមានលិប្ដា០ ហើយមួយទៀតលិប្ដា៥៩។ ពេលគណនាទៅ ឃើញលទ្ធផល ម៉ោង និង នាទីដូចគ្នា។ ដូច្នេះកំណត់យកសុទិនដំបូង។
